version: "3"
services: 
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - ./data:/data/db
    ports:
      - "3306:3306"
    environment:
        MARIADB_DATABASE: file
        MARIADB_USER: Eyob-tad
        MARIADB_PASSWORD: 759864job
        MARIADB_ROOT_HOST: localhost
        MARIADB_RANDOM_ROOT_PASSWORD: 759864job
  server:
    restart: always
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mariadb
  client: 
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links: 
      - server
       